id: IE00AC234
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:25:48+00:00'
last_modified: '2022-06-08T08:45:08.289760+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD83965
  title: སྔ་འགྱུར་རྒྱལ་བ་དཔལ་ཡུལ་བའི་རི་ཆོས་གསུམ་གྱི་ཁྲིད་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    53DA:
      image_group_id: I1KG15600
      title: ''
      total_pages: 334
      order: 1
      base_file: 53DA.txt
    A4A8:
      image_group_id: I1KG15601
      title: ''
      total_pages: 244
      order: 2
      base_file: A4A8.txt
    A600:
      image_group_id: I1KG15602
      title: ''
      total_pages: 276
      order: 3
      base_file: A600.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
